name: CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "165.22.97.26"
        uses: appleboy/ssh-action@master
        with:
          host: '165.22.97.26'
          username: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd public_html
            git pull git@github.com:elkoaditya/sdm-afresto.git master
            git reset --hard
            composer install
